Add integration tests for sorting
ChilliCream/hotchocolate pull request #2313
Opened 2020-09-11 13:55 UTC by PascalSenn

Depends on #2311

2020-09-24 11:27 UTC, michaelstaib commented on src/HotChocolate/Data/test/Data.Sorting.InMemory.Tests/QueryableSortVisitorBooleanTests.cs
> +        private static readonly Foo[] _fooEntities = new[]{
Formatting

private static readonly FooNullable[] _fooNullableEntities = new[]
{
    new FooNullable { Bar = true },
    new FooNullable { Bar = null },
    new FooNullable { Bar = false }
};

2020-09-24 11:27 UTC, michaelstaib commented on src/HotChocolate/Data/test/Data.Sorting.InMemory.Tests/QueryableSortVisitorComparableTests.cs
> +        private static readonly Foo[] _fooEntities = new[]{
Formatting

2020-09-24 11:28 UTC, michaelstaib commented on src/HotChocolate/Data/test/Data.Sorting.InMemory.Tests/QueryableSortVisitorEnumTests.cs
> +            new Foo {BarEnum = FooEnum.BAR},
Formatting:

new Foo { BarEnum = FooEnum.BAR },

2020-09-24 11:28 UTC, michaelstaib commented on src/HotChocolate/Data/test/Data.Sorting.InMemory.Tests/QueryableSortVisitorStringTests.cs
> +            new[] {new Foo {Bar = "testatest"}, new Foo {Bar = "testbtest"}};
Formatting

2020-09-24 21:03 UTC, michaelstaib commented on src/HotChocolate/Data/test/Data.Sorting.SqlLite.Tests/QueryableSortVisitorBooleanTests.cs
> +            new Foo { Bar = true },
Formatting

2020-09-24 21:03 UTC, michaelstaib commented on src/HotChocolate/Data/test/Data.Sorting.SqlLite.Tests/QueryableSortVisitorComparableTests.cs
> +        private static readonly Foo[] _fooEntities = new[]{
Formatting

2020-09-24 21:03 UTC, michaelstaib commented on src/HotChocolate/Data/test/Data.Sorting.SqlLite.Tests/QueryableSortVisitorEnumTests.cs
> +            new Foo {BarEnum = FooEnum.BAR},
formatting 
new Foo {BarEnum = FooEnum.BAR},

2020-09-24 21:04 UTC, michaelstaib commented on src/HotChocolate/Data/test/Data.Sorting.SqlLite.Tests/QueryableSortVisitorStringTests.cs
> +            new[] {new Foo {Bar = "testatest"}, new Foo {Bar = "testbtest"}};
formatting

2020-09-24 21:05 UTC, michaelstaib requested changes
There are some formatting issues left on this one.

2020-09-26 11:45 UTC, PascalSenn commented
@michaelstaib  this one is ready

2020-09-26 17:59 UTC, michaelstaib approved these changes

2020-09-26 19:13 UTC, merged