add tests for filtering with paging
ChilliCream/hotchocolate pull request #2317
Opened 2020-09-11 23:32 UTC by PascalSenn

2020-09-17 22:18 UTC, michaelstaib commented on src/HotChocolate/Data/test/Data.Filters.InMemory.Tests/FilteringAndPaging.cs
> +
formatting

2020-09-17 22:19 UTC, michaelstaib commented on src/HotChocolate/Data/test/Data.Filters.SqlServer.Tests/FilteringAndPaging.cs
> +
formatting

2020-09-17 22:20 UTC, michaelstaib commented on src/HotChocolate/Data/test/Data.Filters.SqlServer.Tests/SchemaCache.cs
> +        : FilterVisitorTestBase,
comma

2020-09-24 21:06 UTC, michaelstaib commented on src/HotChocolate/Data/test/Data.Filters.InMemory.Tests/FilteringAndPaging.cs
> +            new Foo { Bar = true }, new Foo { Bar = false }
Formattting

2020-09-24 21:07 UTC, michaelstaib requested changes
There are some formatting issues on this one.

2020-09-26 11:35 UTC, PascalSenn commented
@michaelstaib  fixed the issues

2020-09-26 17:46 UTC, michaelstaib approved these changes

2020-09-26 18:18 UTC, merged