fix: string for enum value
ChilliCream/hotchocolate pull request #2846
Opened 2021-01-10 16:40 UTC by PascalSenn

Summary of the changes (Less than 80 chars)

- Detail 1
- Detail 2

Addresses #bugnumber (in this specific format)

2021-01-11 22:07 UTC, michaelstaib approved these changes

2021-01-11 22:08 UTC, michaelstaib commented
@PascalSenn can you write an integration tests with enum over variables and literals in the ASP.NET core project. I remember there was an implementation detail why we allowed this.

2021-01-11 22:09 UTC, michaelstaib requested changes
see my comment

2021-01-12 10:52 UTC, PascalSenn commented
There is already such a test:
https://github.com/ChilliCream/hotchocolate/blob/main/src/HotChocolate/AspNetCore/test/AspNetCore.Tests/HttpPostMiddlewareTests.cs#L98-L111

2021-01-13 10:14 UTC, michaelstaib approved these changes

2021-01-13 10:14 UTC, merged