Change PaginationAmount IntType registration
ChilliCream/hotchocolate pull request #2985
Opened 2021-02-01 12:58 UTC by Asshiah

Change PaginationAmount IntType registration no the gateway side in order to prevent the following error on schema reload:
"Operation is not valid due to the current state of the object. (HotChocolate.Types.IntType)"

2021-02-01 17:01 UTC, PascalSenn approved these changes

2021-02-02 23:18 UTC, michaelstaib requested changes
ConfigureSchema is not meant for users but for extensions.

2021-02-02 23:23 UTC, michaelstaib commented
I see what the issue is, but I do not want people to use the underlying schema builder anymore since we are going to refactor it with version 12. So there should be no dependency on it.

What we can do is introduce a new `AddType` overload that allows for a factory approach.


```
AddType(() => new IntType())
```

2021-08-23 06:37 UTC, michaelstaib approved these changes

2021-08-23 06:38 UTC, merged