add NegativeFloatType scalar
ChilliCream/hotchocolate pull request #2996
Opened 2021-02-04 21:16 UTC by wonbyte

- Add PhoneNumber Scalar
Addresses #2968

2021-02-08 21:24 UTC, PascalSenn requested changes
Awesome! 
They really get better every time
just a couple of things :)

2021-02-08 21:24 UTC, PascalSenn commented on src/HotChocolate/Core/src/Types.Scalars/NegativeFloatType.cs
> +
Can we also add `/// <inheritdoc />`

2021-02-08 21:24 UTC, PascalSenn commented on src/HotChocolate/Core/src/Types.Scalars/ThrowHelper.cs
> +        public static SerializationException NegativeFloatType_ParseLiteral_IsNotNegative(IType type)
We have a maximum policy of 100 characters per line :)

2021-02-08 21:24 UTC, PascalSenn commented on website/src/docs/hotchocolate/defining-a-schema/scalars.md
> +The NegativeFloat scalar type represents a signed real number with a value less than 0
This comment does not look right :)

2021-02-08 21:24 UTC, PascalSenn commented on src/HotChocolate/Core/test/Types.Scalars.Tests/NegativeFloatTypeTests.cs
> +        [InlineData(typeof(FloatValueNode), -1.0d, true)]
cann we also add
```
[InlineData(typeof(FloatValueNode), 0d, false)]
```

2021-02-08 21:24 UTC, PascalSenn commented on src/HotChocolate/Core/src/Types/Types/Scalars/FloatTypeBase.cs
> +        }
@michaelstaib  @wonbyte  fixed the base class, could this infer with something?

2021-02-08 21:38 UTC, wonbyte commented
> Awesome!
> They really get better every time
> just a couple of things :)

I'll eventually get it to 0........

2021-02-11 14:10 UTC, PascalSenn approved these changes

2021-02-11 14:11 UTC, merged