fix AnyType stitching
ChilliCream/hotchocolate pull request #2997
Opened 2021-02-05 00:12 UTC by PascalSenn

In stitching we receive ValueNodes from the remote schema
The AnyType has to deserialize these to runtime values. 
We could also leave the serialization away and just handle these cases in deserialization and never properly deserialize
This would be more efficient, but the dictionary could not be evaluated in middlewares & co on the gateway.
Not sure what the better tradeoff is, maybe we could add a flag to the constructor? with the more efficent way?

@michaelstaib should we merge this one in as is and revisit it in 11.2?

Closes #2942. #2691,

2021-02-05 01:59 UTC, PascalSenn commented on src/HotChocolate/Core/src/Types/Types/Scalars/AnyType.cs
> +
line?

2021-02-05 01:59 UTC, PascalSenn commented on src/HotChocolate/Core/src/Types/Types/Scalars/AnyType.cs
> +
line?

2021-02-12 10:17 UTC, michaelstaib submitted a review, later dismissed

2021-02-15 11:18 UTC, PascalSenn commented
/azurepipelines run

2021-02-19 11:13 UTC, michaelstaib requested changes
I will have a go at this fix

2021-03-17 13:17 UTC, michaelstaib approved these changes

2021-03-17 14:14 UTC, merged