Fix Extending Filtering documentation
ChilliCream/hotchocolate pull request #3523
Opened 2021-04-17 15:56 UTC by tobias-tengler

Closes #3442

2021-04-18 23:58 UTC, PascalSenn requested changes
Thanks for the PR @tobias-tengler 
I think this should do

2021-04-18 23:58 UTC, PascalSenn commented on website/src/docs/hotchocolate/api-reference/extending-filtering.md
>      .AddConvention<IFilterConvention>(
```suggestion
    .AddFiltering()
    .AddConvention<IFilterConvention>(
```

2021-04-18 23:58 UTC, PascalSenn commented on website/src/docs/hotchocolate/api-reference/extending-filtering.md
> +        new FilterConvention(
```suggestion
        new FilterConventionExtension(
```

2021-04-19 18:44 UTC, tobias-tengler commented
@PascalSenn this should be ready to go. I'm not sure why your requested changes are still blocking the PR, I already resolved them...

2021-04-19 19:34 UTC, PascalSenn approved these changes

2021-04-19 19:36 UTC, merged