Remember selection of tabs
ChilliCream/hotchocolate pull request #3699
Opened 2021-05-17 20:40 UTC by tobias-tengler

This allows to specify a `groupId` on the `Tabs` component. Changes to a tab with this `groupId` will propagate to all other tabs with that `groupId`. The selection is also persisted in the localStorage and the last selection is restored on the next page visit.

<img src="https://user-images.githubusercontent.com/45513122/118553498-b10b8e00-b760-11eb-9359-350c9c78bca9.gif" height="750px" />

I think this is a nice little UX improvement.

2021-05-17 20:42 UTC, tobias-tengler commented on website/src/components/doc-page/doc-page.tsx
> +    <TabGroupProvider>
I could also scope this closer to the ArticleContent...

2021-05-17 21:02 UTC, tobias-tengler commented
Going to fix the CI error tomorrow, already signed off for today ^^

2021-05-18 06:16 UTC, tobias-tengler commented on website/src/components/mdx/tabs/tab-groups.tsx
> +      value = window.localStorage.getItem(getLocalStorageKey(groupId));
@rstaib I don't have much experience when it comes to SSR/SSG, how could I make it so the selection is actually read from the `localStorage` once it's running in the client's browser? At the moment it always starts out with the `defaultValue` after the first access, subsequent client-routed requests work as expected.

2021-05-18 17:38 UTC, tobias-tengler commented
@rstaib This is ready 🚀

2021-05-21 14:01 UTC, rstaib requested changes
Hey @tobias-tengler,
Looks good and is definitely an UX improvement.
Just added a few minor things. Would be great if you could solve them 👍 
Thank you!

2021-05-21 16:12 UTC, tobias-tengler commented on website/src/components/mdx/tabs/tab-groups.tsx
> +type Groups = {
I chose type only because that's what I always use. No technical reason. As I now see the code base prefers interfaces, so I'll use them.

2021-05-21 16:19 UTC, tobias-tengler commented on website/src/components/mdx/tabs/tab-groups.tsx
> +    if (groups[groupId] === value) return;
I added curly braces, but I prefer to not negate the if as to not add unnecessary nesting to the code below.

2021-05-21 16:57 UTC, tobias-tengler commented on website/src/components/mdx/tabs/tab-groups.tsx
> +export function useIsClient() {
I initially introduced it to fix a re-hydration issue. I found a better way to go about it now, so I've removed this hook.

2021-05-21 16:59 UTC, tobias-tengler commented
@rstaib Thanks for the feedback! :)
I've included all your suggestions.

2021-05-22 12:31 UTC, rstaib requested changes
Almost done just four more very little things. Thank you by the way!

2021-05-22 12:31 UTC, rstaib commented on website/src/components/mdx/tabs/tab-groups.tsx
> +  setGroup: SetGroup;
readonly

2021-05-22 12:31 UTC, rstaib commented on website/src/components/mdx/tabs/tab-groups.tsx
> +  [groupId: string]: string | undefined;
readonly

2021-05-22 12:31 UTC, rstaib commented on website/src/components/mdx/tabs/tab-groups.tsx
> +  }, [groups, groupId]);
dependency -> setActiveTab

2021-05-22 12:31 UTC, rstaib commented on website/src/components/mdx/tabs/tabs.tsx
>    defaultValue: string;
Would be cool, if you could add readonly to all three props

2021-05-22 13:05 UTC, tobias-tengler commented
All done.

2021-05-22 19:55 UTC, rstaib approved these changes
Great!

2021-05-22 19:58 UTC, merged