[WIP]Add Json Scalar
ChilliCream/hotchocolate pull request #3713
Opened 2021-05-20 01:21 UTC by pedro-coelho-ff

Add JsonType to Hotchocolate.Types

Closes #3661

2021-05-21 20:35 UTC, wonbyte commented
@pedro-coelho-ff The scalar needs to only support a `JsonDocument` type.

2021-06-14 21:50 UTC, michaelstaib commented
is this one ready for review?

2021-06-14 23:03 UTC, pedro-coelho-ff commented
> is this one ready for review?

Yes, I believe it is 😅

2021-06-15 06:52 UTC, michaelstaib commented on src/HotChocolate/Core/test/Types.Scalars.Tests/JsonTypeTests.cs
> +
```suggestion
```

2021-06-15 06:54 UTC, michaelstaib commented
on it.

2021-06-15 09:01 UTC, michaelstaib requested changes

2021-06-15 09:01 UTC, michaelstaib commented on src/HotChocolate/Core/src/Types.Scalars/JsonType.cs
> +        public override bool TryDeserialize(object? resultValue, out object? runtimeValue)
TrySerialize: in object / out JsonDocument

2021-06-15 11:20 UTC, michaelstaib commented
I think I will take a swing at this so we get it into the release.

2021-06-15 21:13 UTC, pedro-coelho-ff commented
> I think I will take a swing at this so we get it into the release.

I really appreciate it if you or any other that is more comfortable than me taking this one and putting it in the next release. 😅

2021-06-16 18:31 UTC, wonbyte commented
@michaelstaib let me know if you want me to take it

2021-07-26 16:02 UTC, pedro-coelho-ff commented
@wonbyte and @michaelstaib sorry to bother you with this pull request.
Just a quick note, I had some performance issues with this approach, the solution was to use the AnyType but instead of JsonObject we created a custom JsonConverter and convert it to an object.

2021-08-30 11:36 UTC, closed without merging