WIP: New version selection experience
ChilliCream/hotchocolate pull request #3925
Opened 2021-07-04 16:53 UTC by tobias-tengler

#### Changes

- New dropdown control to select version of current product
- Cleanup of navigation rendering logic

Preview: https://chilly-version-selection.netlify.app/docs/hotchocolate/

#### Todos

- Some code simplifications
- Warning when viewing outdated documentation
- Use of `startsWith`:
![image](https://user-images.githubusercontent.com/45513122/124392963-7baf0580-dcf8-11eb-8c8c-00548092d8d1.png)
- Add version number and product to the title for better SEO

2021-07-05 13:32 UTC, arif-hanif submitted a review, later dismissed

2021-07-05 15:11 UTC, rstaib requested changes

2021-07-05 15:11 UTC, rstaib commented on website/src/components/doc-page/doc-page.tsx
> +                    <div>
Should we do an one-liner?

2021-07-05 15:11 UTC, rstaib commented on website/src/components/doc-page/doc-page.tsx
> +                    <div>
I think it eats up to much space :-)

2021-07-05 15:11 UTC, rstaib commented
Looks pretty good!

2021-07-05 17:03 UTC, tobias-tengler commented
@rstaib done!
Could we maybe first get #3879 in, then I can re-use the variables I declared there here.

2021-07-06 21:58 UTC, rstaib commented
@tobias-tengler merged #3879 👍

2021-07-07 18:07 UTC, rstaib approved these changes
Looks cool!

2021-07-07 18:07 UTC, merged