Added Validation for runtime types
ChilliCream/hotchocolate pull request #4064
Opened 2021-08-08 20:23 UTC by PascalSenn

Summary of the changes (Less than 80 chars)

- Detail 1
- Detail 2

Closes #bugnumber (in this specific format)

2021-08-19 21:01 UTC, michaelstaib commented on src/HotChocolate/Core/src/Types/Types/Interceptors/TypeValidationTypeInterceptor.cs
> +                definition.RuntimeType = typeof(Stub);
why not just object?

2021-08-19 21:06 UTC, michaelstaib requested changes
I think the stub type can go, just use object there... you could even leave the runtime type since you are clearing the dependencies. I have to revisit the dependency clear again since I have reworked this part.

Also, we need an option that disables this interceptor. So, if the runtime check is disabled we should not include this interceptor.

2021-08-24 22:15 UTC, PascalSenn commented
resolved

2021-08-30 10:46 UTC, michaelstaib commented
/AzurePipelines run

2021-08-30 10:55 UTC, michaelstaib approved these changes

2021-08-30 10:56 UTC, merged