fix: Bind types implicit
ChilliCream/hotchocolate pull request #4584
Opened 2021-12-21 23:51 UTC by nelsonprsousa

Summary of the changes (Less than 80 chars)

- Bind SignedByteType, UnsignedIntType, UnsignedLongType, and UnsignedShortType implicit

Closes #4583

2021-12-22 07:06 UTC, michaelstaib commented
You also need to write some unit tests for such a change.

2021-12-22 07:08 UTC, michaelstaib commented
/AzurePipelines run

2021-12-22 16:48 UTC, michaelstaib requested changes
We need tests for this to be merged.

2021-12-22 17:17 UTC, PascalSenn commented
@nelsonprsousa Thanks for the PR :slightly_smiling_face:
Do you want to add a test or should i do this?
it’s basically this
```csharp
public class Query 
{
     public sbyte Byte {get;}
}
```
and
[Fact]
public async Task SByteType_Should_BeBoundImplicity_When_Registered()
{
    // arrange
    // act
    var executor = await new ServiceCollection()
            .AddGraphQL()
            .AddQueryType<Query>()
            .AddType<SByteType>() 
            .BuildRequestExecutorAsync();

    // assert
    executor.Schema.Print().MatchSnapshot();
}

2021-12-22 20:01 UTC, michaelstaib commented
Well said @PascalSenn :D I was heads down in my own PRs and did not fully really explain and appreciate this :) 

We really appreciate and value any new contributor 💯  So thanks for your contribution. Pascal outlined the rest.

2021-12-22 20:45 UTC, nelsonprsousa commented
> Well said @PascalSenn :D I was heads down in my own PRs and did not fully really explain and appreciate this :)
> 
> We really appreciate and value any new contributor 💯 So thanks for your contribution. Pascal outlined the rest.

No worries @michaelstaib 

Just pushed a new commit with 4 new unit tests. Also, we are now using file-scoped namespaces like it is specified by IDE0161.

cc @PascalSenn

2021-12-22 22:33 UTC, michaelstaib commented on src/HotChocolate/Core/test/Types.Scalars.Tests/ScalarTypeTestBase.cs
> +                .BuildRequestExecutorAsync();
```suggestion
        IRequestExecutor executor = await new ServiceCollection()
            .AddGraphQL()
            .AddQueryType<TDefaultClass>()
            .AddType<TType>()
            .BuildRequestExecutorAsync();
```

2021-12-22 22:34 UTC, michaelstaib approved these changes
@PascalSenn can you have another look and merge? So far it looks good to me.

2021-12-22 22:34 UTC, michaelstaib commented
/AzurePipelines run

2021-12-24 13:49 UTC, PascalSenn commented on src/HotChocolate/Core/test/Types.Scalars.Tests/ScalarTypeTestBase.cs
> +
Can we remove those empty lines? :)

2021-12-24 17:45 UTC, nelsonprsousa commented on src/HotChocolate/Core/test/Types.Scalars.Tests/ScalarTypeTestBase.cs
> +
Done 👍

2021-12-25 13:35 UTC, PascalSenn approved these changes

2021-12-25 13:36 UTC, PascalSenn commented on src/HotChocolate/Core/test/Types.Scalars.Tests/ScalarTypeTestBase.cs
> +
awesome!

2021-12-30 17:49 UTC, PascalSenn approved these changes
Looks good! thanks for the contribution :)

2021-12-30 17:49 UTC, PascalSenn commented
/AzurePipelines run

2021-12-30 20:18 UTC, merged