Update Gatsby and fix scroll issue
ChilliCream/hotchocolate pull request #4752
Opened 2022-02-11 20:10 UTC by tobias-tengler

A user reported the inability to scroll using arrow keys, with this change the website can be scrolled again, albeit the scrollbar is now partially hidden behind the header.

2022-02-11 20:11 UTC, tobias-tengler commented
@rstaib Is it intentional that the .yarn directory with its cache was checked in?

2022-02-12 13:13 UTC, rstaib requested changes
introduces another issue in regard to navigation height

2022-02-12 13:13 UTC, rstaib commented on website/src/components/misc/global-style.tsx
> +  }
empty space

2022-02-12 13:13 UTC, rstaib commented on website/src/components/misc/global-style.tsx
> -      height: 100vh;
removing height leads to another issue, where navigation does not take anymore the entire height of the content area.

2022-02-12 13:13 UTC, rstaib commented on website/src/components/misc/global-style.tsx
> -        height: 100vh;
same here

2022-08-17 14:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ChilliCream/hotchocolate?pullRequest=4752) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ChilliCream/hotchocolate?pullRequest=4752) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ChilliCream/hotchocolate?pullRequest=4752) it.</sub>

2022-12-16 10:47 UTC, closed without merging